<a href="https://colab.research.google.com/github/anishraj-38/Python/blob/main/Apple_I_Phone.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Iphone Analysis**

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

In [7]:
df=pd.read_csv("/content/apple_products.csv")
df

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB
...,...,...,...,...,...,...,...,...,...,...,...
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,24,95909,8161,MOBFWQ6BR3MK7AUG,4.5,4 GB
58,"APPLE iPhone 11 (Purple, 64 GB)",https://www.flipkart.com/apple-iphone-11-purpl...,Apple,46999,54900,14,43470,3331,MOBFWQ6BTFFJKGKE,4.6,4 GB
59,"APPLE iPhone 11 (White, 64 GB)",https://www.flipkart.com/apple-iphone-11-white...,Apple,46999,54900,14,43470,3331,MOBFWQ6BVWVEH3XE,4.6,4 GB
60,"APPLE iPhone 11 (Black, 64 GB)",https://www.flipkart.com/apple-iphone-11-black...,Apple,46999,54900,14,43470,3331,MOBFWQ6BXGJCEYNY,4.6,4 GB
61,"APPLE iPhone 11 (Red, 64 GB)",https://www.flipkart.com/apple-iphone-11-red-6...,Apple,46999,54900,14,43470,3331,MOBFWQ6BYYV3FCU7,4.6,4 GB

In [8]:
df.isnull().sum()

Product Name           0
Product URL            0
Brand                  0
Sale Price             0
Mrp                    0
Discount Percentage    0
Number Of Ratings      0
Number Of Reviews      0
Upc                    0
Star Rating            0
Ram                    0
dtype: int64

In [9]:
df.describe()

,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Star Rating
count,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000
mean,80073.887097,88058.064516,9.951613,22420.403226,1861.677419,4.575806
std,34310.446132,34728.825597,7.608079,33768.589550,2855.883830,0.059190
min,29999.000000,39900.000000,0.000000,542.000000,42.000000,4.500000
25%,49900.000000,54900.000000,6.000000,740.000000,64.000000,4.500000
50%,75900.000000,79900.000000,10.000000,2101.000000,180.000000,4.600000
75%,117100.000000,120950.000000,14.000000,43470.000000,3331.000000,4.600000
max,140900.000000,149900.000000,29.000000,95909.000000,8161.000000,4.700000

In [10]:
df.drop_duplicates

<bound method DataFrame.drop_duplicates of                                 Product Name  \
0          APPLE iPhone 8 Plus (Gold, 64 GB)
1   APPLE iPhone 8 Plus (Space Grey, 256 GB)
2       APPLE iPhone 8 Plus (Silver, 256 GB)
3            APPLE iPhone 8 (Silver, 256 GB)
4              APPLE iPhone 8 (Gold, 256 GB)
..                                       ...
57            APPLE iPhone SE (Black, 64 GB)
58           APPLE iPhone 11 (Purple, 64 GB)
59            APPLE iPhone 11 (White, 64 GB)
60            APPLE iPhone 11 (Black, 64 GB)
61              APPLE iPhone 11 (Red, 64 GB)

                                          Product URL  Brand  Sale Price  \
0   https://www.flipkart.com/apple-iphone-8-plus-g...  Apple       49900
1   https://www.flipkart.com/apple-iphone-8-plus-s...  Apple       84900
2   https://www.flipkart.com/apple-iphone-8-plus-s...  Apple       84900
3   https://www.flipkart.com/apple-iphone-8-silver...  Apple       77000
4   https://www.flipkart.com/apple-iphone-8-gold-2...  Apple       77000
..                                                ...    ...         ...
57  https://www.flipkart.com/apple-iphone-se-black...  Apple       29999
58  https://www.flipkart.com/apple-iphone-11-purpl...  Apple       46999
59  https://www.flipkart.com/apple-iphone-11-white...  Apple       46999
60  https://www.flipkart.com/apple-iphone-11-black...  Apple       46999
61  https://www.flipkart.com/apple-iphone-11-red-6...  Apple       46999

      Mrp  Discount Percentage  Number Of Ratings  Number Of Reviews  \
0   49900                    0               3431                356
1   84900                    0               3431                356
2   84900                    0               3431                356
3   77000                    0              11202                794
4   77000                    0              11202                794
..    ...                  ...                ...                ...
57  39900                   24              95909               8161
58  54900                   14              43470               3331
59  54900                   14              43470               3331
60  54900                   14              43470               3331
61  54900                   14              43470               3331

                 Upc  Star Rating   Ram
0   MOBEXRGV7EHHTGUH          4.6  2 GB
1   MOBEXRGVAC6TJT4F          4.6  2 GB
2   MOBEXRGVGETABXWZ          4.6  2 GB
3   MOBEXRGVMZWUHCBA          4.5  2 GB
4   MOBEXRGVPK7PFEJZ          4.5  2 GB
..               ...          ...   ...
57  MOBFWQ6BR3MK7AUG          4.5  4 GB
58  MOBFWQ6BTFFJKGKE          4.6  4 GB
59  MOBFWQ6BVWVEH3XE          4.6  4 GB
60  MOBFWQ6BXGJCEYNY          4.6  4 GB
61  MOBFWQ6BYYV3FCU7          4.6  4 GB

[62 rows x 11 columns]>

In [11]:
high_rating=df.sort_values(by=['Star Rating'],ascending=False)

In [12]:
high_rating.head(10)
print(high_rating['Product Name'])

15               APPLE iPhone 11 Pro Max (Gold, 64 GB)
20     APPLE iPhone 11 Pro Max (Midnight Green, 64 GB)
17         APPLE iPhone 11 Pro Max (Space Grey, 64 GB)
16    APPLE iPhone 11 Pro Max (Midnight Green, 256 GB)
14              APPLE iPhone 11 Pro Max (Gold, 256 GB)
                            ...
52                      APPLE iPhone SE (White, 64 GB)
53                     APPLE iPhone SE (Black, 128 GB)
57                      APPLE iPhone SE (Black, 64 GB)
54                     APPLE iPhone SE (White, 128 GB)
55                       APPLE iPhone SE (Red, 128 GB)
Name: Product Name, Length: 62, dtype: object

In [13]:
iphones=high_rating['Product Name'].value_counts()
label=iphones.index
counts=high_rating['Number Of Ratings']
fig=px.bar(high_rating,x=label,y=counts,title='Iphone Rating')
fig.show()

In [14]:
iphones=high_rating['Product Name'].value_counts()
label=iphones.index
counts=high_rating['Number Of Reviews']
fig=px.bar(high_rating,x=label,y=counts,title='Iphone Reviews')
fig.show()

In [20]:
fig=px.scatter(data_frame=df,x='Number Of Ratings',y='Sale Price',title='Number of sales on the basis of rating',size='Discount Percentage',trendline='ols')
fig.show()

In [25]:
figure = px.scatter(data_frame=df,x='Number Of Ratings',y='Discount Percentage',size='Sale Price',title='Number of sales on the basis of discount',trendline='ols')
figure.show()